Password Manager: wk::Database Class Reference
wk::Database Class Reference
Utilities
Manages a collection of password and PIN entries.
#include <Database.hpp>
Public Member Functions
Database (const std::string &password)
Constructs a Database with a master password.
bool titleExists (const std::string &title) const
Checking for existing titles. Using in 'PasswordManager::newEntry' to ensure that each new entry added to the database has a unique title.
void addEntry (const std::variant< PasswordEntry, PinEntry > &entry)
Adds a new entry to the database.
void removeEntry (const std::string &title)
Removes an entry from the database by title.
void displayEntries () const
Displays all entries in the database.
void saveToFile (const std::string &filename)
Saves all entries to a file.
void loadFromFile (const std::string &filename)
Loads entries from a file.
Private Attributes
std::vector< std::variant< PasswordEntry, PinEntry > > entries
Encryptor encryptor
Detailed Description
Manages a collection of password and PIN entries.
The Database class provides functionalities to add, remove, display, and persist entries. It supports both password and PIN entries using variants.
Constructor & Destructor Documentation
Database()
wk::Database::Database (const std::string & password)
Constructs a Database with a master password.
Parameters
password The master password to encrypt/decrypt file.
Member Function Documentation
addEntry()
void wk::Database::addEntry (const std::variant< PasswordEntry, PinEntry > & entry)
Adds a new entry to the database.
Parameters
entry A variant containing either a PasswordEntry or PinEntry.
References entries.
displayEntries()
void wk::Database::displayEntries () const
Displays all entries in the database.
References entries.
loadFromFile()
void wk::Database::loadFromFile (const std::string & filename)
Loads entries from a file.
Parameters
filename The file to load entries from.
References wk::Encryptor::decryptData(), encryptor, entries, wk::PasswordEntry::load(), and wk::PinEntry::load().
removeEntry()
void wk::Database::removeEntry (const std::string & title)
Removes an entry from the database by title.
Parameters
title The title of the entry to remove.
References entries.
saveToFile()
void wk::Database::saveToFile (const std::string & filename)
Saves all entries to a file.
Parameters
filename The file to save entries into.
References wk::Encryptor::encryptData(), encryptor, and entries.
titleExists()
bool wk::Database::titleExists (const std::string & title) const
Checking for existing titles. Using in 'PasswordManager::newEntry' to ensure that each new entry added to the database has a unique title.
References entries.
Member Data Documentation
encryptor
Encryptor wk::Database::encryptor private
Handles encryption and decryption.
entries
std::vector<std::variant<PasswordEntry, PinEntry> > wk::Database::entries private
Container for storing database entries.
The documentation for this class was generated from the following files:
include/Database.hpp
src/Database.cpp