Password Manager: wk::PasswordManager Class Reference
wk::PasswordManager Class Reference
Handles the main menu for user interaction.
#include <PasswordManager.hpp>
Public Member Functions
PasswordManager (const std::string &dbName, const std::string &masterPassword)
Parametrized constructor.
void run ()
Runs the password manager interface. * This method presents a menu to the user and processes the user's choices.
Private Member Functions
void displayMenu ()
Displays the main menu options. * This method displays the list of actions the user can choose from, such as adding an entry, removing an entry, displaying entries, saving the database, or exiting.
void newEntry ()
Handle the 'Database::addEntry' Adds a new entry to the database.
void deleteEntry ()
Handle the 'Database::removeEntry' Removes an entry from the database.
void saveDB ()
Handle the 'Database::saveToFile' Saves the current database to a file.
void loadDB ()
Handle the 'Database::loadFromFile' Loads the database from a file.
Private Attributes
Database db
std::string filename
Detailed Description
Handles the main menu for user interaction.
The PasswordManager class is responsible for interacting with the Database class to manage password entries. It provides logic of load and saving the database from a file and also provides functionality to add, remove, and display password entries.
Constructor & Destructor Documentation
PasswordManager()
wk::PasswordManager::PasswordManager (const std::string & dbName, const std::string & masterPassword)
Parametrized constructor.
This constructor initializes the password manager and sets up the database.
Parameters
dbName The relative path and name of the database file (in UNIX-style path format)
masterPassword The master password used to access the database.
Member Function Documentation
deleteEntry()
void wk::PasswordManager::deleteEntry () private
Handle the 'Database::removeEntry' Removes an entry from the database.
References db, and wk::Database::removeEntry().
displayMenu()
void wk::PasswordManager::displayMenu () private
Displays the main menu options. * This method displays the list of actions the user can choose from, such as adding an entry, removing an entry, displaying entries, saving the database, or exiting.
loadDB()
void wk::PasswordManager::loadDB () private
Handle the 'Database::loadFromFile' Loads the database from a file.
References db, filename, and wk::Database::loadFromFile().
newEntry()
void wk::PasswordManager::newEntry () private
Handle the 'Database::addEntry' Adds a new entry to the database.
References wk::Database::addEntry(), db, and wk::Database::titleExists().
run()
void wk::PasswordManager::run ()
Runs the password manager interface. * This method presents a menu to the user and processes the user's choices.
References db, deleteEntry(), wk::Database::displayEntries(), displayMenu(), loadDB(), newEntry(), and saveDB().
saveDB()
void wk::PasswordManager::saveDB () private
Handle the 'Database::saveToFile' Saves the current database to a file.
References db, filename, and wk::Database::saveToFile().
Member Data Documentation
db
Database wk::PasswordManager::db private
The Database object.
filename
std::string wk::PasswordManager::filename private
UNIX-style path format for database
The documentation for this class was generated from the following files:
include/PasswordManager.hpp
src/PasswordManager.cpp